version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9.9

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install selenium==4.16.0 Flask==3.0.0 click==7.1.2 itsdangerous==1.1.0 Jinja2==3.0.2 MarkupSafe==2.0.1 Werkzeug==2.0.0 pytest

      # Run Selenium tests
      - run:
          name: Run Selenium tests
          command: |
            python tests/selenium_driver_code.py

workflows:
  version: 2
  build:
    jobs:
      - build
