version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.9

    steps:
      - checkout

      # Install Chrome and ChromeDriver
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            sudo apt update
            sudo apt install -y chromium-chromedriver
            sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install selenium==4.16.0 Flask click itsdangerous Jinja2 MarkupSafe Werkzeug3 pytest

      # Run Selenium tests
      - run:
          name: Run Selenium tests
          command: |
            python tests/selenium_driver_code.py

workflows:
  version: 2
  build:
    jobs:
      - build
