version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9.9

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install selenium==4.16.0 Flask==3.0.0

      # Run Selenium tests
      - run:
          name: Run Selenium tests
          command: |
            python tests/selenium_test.py

workflows:
  version: 2
  build:
    jobs:
      - build

