version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9.9

    steps:
      - checkout

      # Install Chromedriver
      - run:
          name: Install Chromedriver
          command: |
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver.zip
            chmod +x chromedriver
            mv chromedriver /usr/local/bin/

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install selenium Flask click itsdangerous Jinja2 MarkupSafe Werkzeug pytest

      # Run Selenium tests
      - run:
          name: Run Selenium tests
          command: |
            python tests/selenium_driver_code.py

workflows:
  version: 2
  build:
    jobs:
      - build
