version: 2.1

jobs:
  build:
    docker:
      - image: selenium/standalone-chrome:latest  # Includes Python and Chrome

    steps:
      - checkout

      # Install project dependencies (if any)
      - run:
          name: Install project dependencies (optional)
          command: |
            pip install --upgrade pip  # Upgrade pip (optional)
            pip install pytest Flask click itsdangerous Jinja2 MarkupSafe Werkzeug

      # Run your Selenium tests
      - run:
          name: Run Selenium tests
          command: |
            python tests/selenium_driver_code.py

workflows:
  version: 2
  build:
    jobs:
      - build
