version: 2.1

jobs:
  build:
    docker:
      - image: python:3.9.9

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install --upgrade pip
            pip install selenium Flask click itsdangerous Jinja2 MarkupSafe Werkzeug pytest

      # Run Selenium tests
      - run:
          name: Run Selenium tests
          command: |
            python tests/selenium_driver_code.py

workflows:
  version: 2
  build:
    jobs:
      - build
